name: gh-pages

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.22.2"

      - name: Generate env file
        run: |
          touch env
          printf "SUPABASE_URL=%s\n" "${{ secrets.SUPABASE_URL }}" > web/env
          printf "SUPABASE_ANONKEY=%s\n" "${{ secrets.SUPABASE_ANONKEY }}" >> web/env

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /injicare_event_security/
    
